"""
Keyboards package for ByMeVPN bot
"""

from .inline import (
    main_menu_keyboard,
    expired_subscription_keyboard,
    plan_type_keyboard,
    period_keyboard,
    payment_methods_keyboard,
    instructions_keyboard,
    legal_menu_keyboard,
    about_keyboard,
    back_to_menu_keyboard,
    referral_keyboard,
    referral_details_keyboard,
    instruction_navigation_keyboard,
    tournaments_keyboard,
    tournament_details_keyboard,
    settings_keyboard,
    admin_extended_keyboard,
    legal_download_keyboard,
    user_profile_keyboard,
    user_settings_keyboard,
    # Legacy compatibility functions
    main_menu_keyboard_legacy,
    expired_subscription_keyboard_legacy,
    plan_type_keyboard_legacy,
    period_keyboard_legacy,
    payment_methods_keyboard_legacy,
    instructions_keyboard_legacy,
    legal_menu_keyboard_legacy,
    about_keyboard_legacy,
    back_to_menu_keyboard_legacy,
)

__all__ = [
    "main_menu_keyboard",
    "expired_subscription_keyboard",
    "plan_type_keyboard",
    "period_keyboard",
    "payment_methods_keyboard",
    "instructions_keyboard",
    "legal_menu_keyboard",
    "about_keyboard",
    "back_to_menu_keyboard",
    "referral_keyboard",
    "referral_details_keyboard",
    "instruction_navigation_keyboard",
    "tournaments_keyboard",
    "tournament_details_keyboard",
    "settings_keyboard",
    "admin_extended_keyboard",
    "legal_download_keyboard",
    "user_profile_keyboard",
    "user_settings_keyboard",
    # Legacy compatibility functions
    "main_menu_keyboard_legacy",
    "expired_subscription_keyboard_legacy",
    "plan_type_keyboard_legacy",
    "period_keyboard_legacy",
    "payment_methods_keyboard_legacy",
    "instructions_keyboard_legacy",
    "legal_menu_keyboard_legacy",
    "about_keyboard_legacy",
    "back_to_menu_keyboard_legacy",
]